services:
  directus:
    image: directus/directus:11.8.0
    ports:
      - 8055:8055
    volumes:
      - ./:/directus/extensions/tiptap
    env_file: ".env.test"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8055/server/health || exit 1"]
      start_period: 20s
