name: Generate changeset for Renovate

on:
  merge_group:
  pull_request_target:
    paths:
      - '.github/workflows/changesets-renovate.yml'
      - '**/pnpm-lock.yaml'
      - '**/package.json'

jobs:
  generate-changeset:
    runs-on: ubuntu-24.04
    if: github.actor == 'renovate[bot]' && github.repository == 'gbicou/directus-extension-tiptap'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: '${{ secrets.PAT }}'
          fetch-depth: 2

      - name: Git Identity
        run: |
          git config --global user.name 'renovate[bot]'
          git config --global user.email 'renovate[bot]@users.noreply.github.com'

      - name: Prepare and Build
        uses: ./.github/actions/prepare
        with:
          tiptap-pro-token: ${{ secrets.TIPTAP_PRO_TOKEN }}
          build: false

      - name: Run changesets-renovate
        run: pnpm dlx @scaleway/changesets-renovate
