name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node and pnpm
        uses: ./.github/actions/prepare

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --no-git-checks --provenance
