name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          tiptap-pro-token: ${{ secrets.TIPTAP_PRO_TOKEN }}

      - name: Build
        run: pnpm build

      - name: Start docker services
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: docker-compose.test.yaml
          up-flags: '--wait'

      - name: Run tests
        run: pnpm test
